Fixed and added hyperlinks
CSClubOfStanState/csclub-website pull request #19
Opened 2022-09-25 11:00 UTC by Sangresz

I added hyperlinks on the archive.html page regarding the authors.
On the footers of every page i fixed some hyperlinks

2022-09-25 11:19 UTC, ggiande commented on archives/archive.html
> -      <p class="lead">NextJS Workshop (Led by Giancarlo Garcia Deleon)</p>
External pages should target="__blank"

2022-09-25 11:22 UTC, ggiande commented on index.html
> +            <a class="nav-link" href="/archives/archive.html#">Archive</a>
the . is needed so it know's it's going into a directory

2022-09-25 11:23 UTC, ggiande requested changes
Thanks for fixing the spacing issue on contact.html's footer.
- [ ] Change PR to merge to development branch
- [ ] Have href's that go to external sites, target="__blank"
- [ ] Changing URL of script breaks it
- [ ] Fix Archive link address & Change color to match the other links

2022-09-25 12:12 UTC, Sangresz commented
I had the external sites have the target attribute, i fixed the different color of the archive link

2022-09-27 07:25 UTC, ggiande requested changes
Found some minor issues.

2022-09-27 07:25 UTC, ggiande commented on officers.html
> +            <a href="/#" class="nav-link px-2 text-muted">Home</a>
- [ ] Revert to `<a href="#" class="nav-link px-2 text-muted">Home</a>` because the new code opens the file directory

2022-09-27 07:25 UTC, ggiande commented on officers.html
> +            <a href="/#Blog" class="nav-link px-2 text-muted">Blog</a>
- [ ] Change to go back to index.html #Blog

2022-09-27 07:25 UTC, ggiande commented on officers.html
> +            <a href="/#Resources" class="nav-link px-2 text-muted">Resources</a>
- [ ] Change to go back index.html #resources

2022-10-03 17:08 UTC, ggiande commented
Hello @Sangresz Please pull changes from the development branch and resolve merge conflicts.

2022-10-03 17:26 UTC, Sangresz commented
> 

how can i pull from the development branch?

2022-10-03 18:54 UTC, ggiande commented
From your current branch, run the following command: `git pull origin development`
Git will let you know that you have conflicts and that you'll need to address some conflicts. Checkout the following article on [resolving merge conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts).

2022-10-04 22:22 UTC, ggiande commented
Oh dear :/ when you forked and created a new branch was it off of development or main?

2022-10-05 17:25 UTC, ggiande commented
I'm assuming it's on the main branch. Try 'git pull origin main'

2022-10-06 13:25 UTC, Sangresz commented
idk, how can I check?

2022-10-06 13:29 UTC, ggiande commented
You can check your current branch by running `git branch`. If you are on main, run `git pull origin main` and follow the instructions to resolve any merge conflict.

2022-10-07 10:03 UTC, Sangresz commented
i am not on main, i am on the branch FixAuthorLinks

2022-10-09 05:38 UTC, ggiande commented
FixAuthorLinks is likely a branch that originated from main, hence why we pull changes from main. Checkout the following [link on branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches) and a bit about [committing changes to a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork).

2024-05-23 10:55 UTC, closed without merging